#!/usr/bin/env python3
"""Generate static references for the bilingual OEM catalog (kept by resource shrinkers)."""
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
names = sorted(item.get('name') for file in (root / 'app/src/main/res/values').glob('oem_*.xml')
               for item in ET.parse(file).getroot() if item.tag == 'string')
target = root / 'app/src/main/java/com/ahwotel/OemTextResources.kt'
target.write_text('package com.ahwotel\n\n// Generated by scripts/update-oem-resources.py from the OEM XML catalog.\n'
                  'internal val OemTextResources: Map<String, Int> = mapOf(\n'
                  + ''.join(f'    "{name}" to R.string.{name},\n' for name in names) + ')\n')
